# Generated by Django 5.2.14 on 2026-06-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='editor_preference',
            field=models.CharField(choices=[('html', 'Visual editor'), ('markdown', 'Markdown')], default='html', max_length=10),
        ),
    ]
