# Generated by Django 5.2.14 on 2026-07-01 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('github_owner', models.CharField(max_length=200)),
                ('github_repo', models.CharField(max_length=200)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('docs_path', models.CharField(default='docs', max_length=200)),
                ('nav_tree', models.JSONField(blank=True, default=list)),
                ('sync_status', models.CharField(choices=[('pending', 'Never synced'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('github_owner', 'github_repo')},
            },
        ),
        migrations.CreateModel(
            name='DocPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('slug_path', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('nav_label', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('raw_markdown', models.TextField()),
                ('rendered_html', models.TextField(blank=True)),
                ('github_sha', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='docs.project')),
            ],
            options={
                'ordering': ['order', 'slug_path'],
                'unique_together': {('project', 'slug_path')},
            },
        ),
    ]
