# Generated by Django 5.2.14 on 2026-07-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docpage",
            name="rendered_html",
        ),
    ]
