# Generated by Django 5.2.14 on 2026-07-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_remove_docpage_rendered_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='default_branch',
            field=models.CharField(blank=True, default='main', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='docs_path',
            field=models.CharField(blank=True, default='docs', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
