# Generated by Django 5.2.14 on 2026-07-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_project_default_branch_alter_project_docs_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Public docs are viewable by anyone with the link. Private docs are visible only to you.'),
        ),
    ]
