# Generated by Django 5.2.14 on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_project_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_private',
            field=models.BooleanField(default=False, help_text='True when the connected GitHub repository itself is private.'),
        ),
    ]
