# Generated by Django 5.2.14 on 2026-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0005_project_github_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Public docs are viewable by anyone with the link. Private docs are visible only to you. Private GitHub repos stay private.",
            ),
        ),
    ]
