# Generated by Django 5.2.14 on 2026-06-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_author_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('html', 'Rich HTML')], default='markdown', max_length=10),
        ),
    ]
