# Generated by Django 5.2.14 on 2026-06-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editor_preference',
            field=models.CharField(choices=[('html', 'Visual editor'), ('markdown', 'Markdown')], default='html', max_length=10),
        ),
    ]
