# Generated by Django 5.2.14 on 2026-06-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_editor_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='editor_preference',
        ),
    ]
